services:
  - type: web
    name: flexpilot-ide
    env: node
    buildCommand: NODE_OPTIONS="--max-old-space-size=4096" npm install --ignore-scripts && npm run download-builtin-extensions && NODE_OPTIONS="--max-old-space-size=4096" npm run compile-build && NODE_OPTIONS="--max-old-space-size=4096" npm run compile-web && NODE_OPTIONS="--max-old-space-size=4096" npm run minify-vscode-reh-web
    startCommand: npm run render:start
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: VSCODE_SKIP_PRELAUNCH
        value: "1"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096"
    healthCheckPath: /
    autoDeploy: true

